    @Test
    public void testIterateWithoutArgument() throws Exception {
        try {
            rootNode.iterate();
            fail("Exception is excepted");
        }
        catch (UnsupportedOperationException ex) {
            assertEquals("Invalid exception message",
                    "Operation is not supported",
                    ex.getMessage());
        }
    }

