    public void valid2()
        throws java.rmi.RemoteException;

