    private void myFunc()
      throws Exception
    {
    }

